kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: pod-checkpointer-operator
  namespace: openshift-pod-checkpointer
subjects:
  - kind: ServiceAccount
    name: pod-checkpointer-operator
    namespace: openshift-pod-checkpointer
roleRef:
  kind: Role
  name: pod-checkpointer-operator
  apiGroup: rbac.authorization.k8s.io
