kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: pod-checkpointer-operator
  namespace: kube-system
rules:
- apiGroups:
  - pod.checkpointer.operator.openshift.io
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - "*"

---

apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: kube-system
  name: kube-controller-manager

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: pod-checkpointer-operator
  namespace: kube-system
subjects:
- kind: ServiceAccount
  name: pod-checkpointer-operator
  namespace: kube-system
roleRef:
  kind: Role
  name: pod-checkpointer-operator
  apiGroup: rbac.authorization.k8s.io


